services:
  cctl:
    build:
      context: ../.
      dockerfile: docker/Dockerfile
      args:
        NODE_GITBRANCH: release-1.5.6
        CLIENT_GITBRANCH: release-2.0.0
    container_name: cspr-cctl
    image: rom3dius/cctl-node-network:v156
    ports:
      - 25101:25101
      - 11101:11101
      - 14101:14101
      - 18101:18101
    healthcheck:
      test: |
        curl --location 'http://localhost:11101/rpc' \
          --header 'Content-Type: application/json' \
          --data '{
              "id": "383766004",
              "jsonrpc": "2.0",
              "method": "info_get_status",
              "params": []
          }' | jq '.result.available_block_range.high' | grep -q '^1' && echo "Success" && exit 0 || echo "Error" && exit 1
      interval: 5s
      retries: 5
      start_period: 5s